name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Minecraft version to download (e.g., 1.19.4)'
        required: true
        default: '1.19.4'
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install system dependencies
      run: sudo apt-get install -y xvfb wget curl jq
      
    - name: Get Minecraft version manifest
      id: get-manifest
      run: |
        # Get the version manifest
        VERSION="${{ github.event.inputs.version || '1.19.4' }}"
        echo "Selected version: $VERSION"
        
        # Fetch version manifest
        MANIFEST_URL="https://launchermeta.mojang.com/mc/game/version_manifest.json"
        VERSION_URL=$(curl -s $MANIFEST_URL | jq -r ".versions[] | select(.id==\"$VERSION\") | .url")
        
        if [ "$VERSION_URL" = "null" ] || [ -z "$VERSION_URL" ]; then
          echo "Error: Version $VERSION not found"
          exit 1
        fi
        
        echo "version-url=$VERSION_URL" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Download Minecraft client jar
      run: |
        VERSION_URL="${{ steps.get-manifest.outputs.version-url }}"
        VERSION="${{ steps.get-manifest.outputs.version }}"
        
        # Get the client download URL
        CLIENT_URL=$(curl -s $VERSION_URL | jq -r '.downloads.client.url')
        
        if [ "$CLIENT_URL" = "null" ] || [ -z "$CLIENT_URL" ]; then
          echo "Error: Could not find client download URL"
          exit 1
        fi
        
        # Download the client jar
        echo "Downloading Minecraft client $VERSION..."
        wget -O "minecraft-$VERSION.jar" "$CLIENT_URL"
        
        # Verify download
        if [ ! -f "minecraft-$VERSION.jar" ]; then
          echo "Error: Failed to download Minecraft client"
          exit 1
        fi
        
        echo "Successfully downloaded minecraft-$VERSION.jar"
        ls -la "minecraft-$VERSION.jar"
        
    - name: Run tests
      run: xvfb-run --auto-servernum npm test
      
    - name: Generate render files
      run: |
        # Add your file generation logic here
        # This is where you would process the Minecraft jar and generate your render files
        mkdir -p generated-files
        
        # Example: Extract or process files from the Minecraft jar
        # You might want to extract textures, models, or other assets
        echo "Processing Minecraft jar and generating render files..."
        
        # Copy any generated files to the output directory
        cp -r test-data/* generated-files/ 2>/dev/null || true
        
        # Remove unwanted files
        rm -f generated-files/test.jar 2>/dev/null || true
        rm -f generated-files/.gitignore 2>/dev/null || true
        
        echo "Generated files:"
        ls -la generated-files/
        
    - name: Create release package
      run: |
        VERSION="${{ steps.get-manifest.outputs.version }}"
        PACKAGE_NAME="minecraft-render-$VERSION"
        
        # Create release directory
        mkdir -p release/$PACKAGE_NAME
        
        # Copy generated files
        cp -r generated-files/* release/$PACKAGE_NAME/
        
        # Copy the Minecraft jar
        cp "minecraft-$VERSION.jar" "release/$PACKAGE_NAME/"
        
        # Create a README for the release
        cat > "release/$PACKAGE_NAME/README.md" << EOF
        # Minecraft Render - Version $VERSION
        
        This package contains render files generated from Minecraft $VERSION.
        
        ## Contents
        - Generated render files
        - Minecraft client jar ($VERSION)
        
        Generated on: $(date -u)
        EOF
        
        # Create zip package
        cd release
        zip -r "../$PACKAGE_NAME.zip" "$PACKAGE_NAME/"
        cd ..
        
        echo "Created release package: $PACKAGE_NAME.zip"
        ls -la "$PACKAGE_NAME.zip"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: minecraft-render-${{ steps.get-manifest.outputs.version }}
        path: |
          generated-files/*
          minecraft-*.jar
          *.zip
        retention-days: 30
        
    - name: Create Release
      if: github.event_name == 'workflow_dispatch'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get-manifest.outputs.version }}-${{ github.run_number }}
        release_name: Minecraft Render v${{ steps.get-manifest.outputs.version }}
        body: |
          ## Minecraft Render - Version ${{ steps.get-manifest.outputs.version }}
          
          Automatically generated render package for Minecraft ${{ steps.get-manifest.outputs.version }}.
          
          ### Changes
          - Downloaded Minecraft client jar version ${{ steps.get-manifest.outputs.version }}
          - Generated render files
          - Created release package
          
          **Build:** ${{ github.run_number }}
          **Commit:** ${{ github.sha }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./minecraft-render-${{ steps.get-manifest.outputs.version }}.zip
        asset_name: minecraft-render-${{ steps.get-manifest.outputs.version }}.zip
        asset_content_type: application/zip
